let colors = [
    "navy",
    "midnightblue",
    "darkslateblue",
    "indigo",
    "purple",
    "darkmagenta",
    "darkviolet",
    "mediumblue",
    "steelblue",
    "royalblue",
    "cornflowerblue",
    "deepskyblue",
    "teal",
    "darkturquoise",
    "cadetblue",
    "slategray",
    "darkolivegreen",
    "forestgreen",
    "darkgreen",
    "mediumseagreen",
    "seagreen",
    "olivedrab",
    "darkgoldenrod",
    "goldenrod",
    "saddlebrown",
    "maroon",
    "firebrick",
    "crimson",
    "indianred",
    "brown",
    "darkred"
];

export default colors;