// File Relative Path: pages/_app.tsx
import React, { useState, useEffect, useRef } from 'react';
import { useRouter } from 'next/router';
import type { AppProps } from 'next/app';
import Script from 'next/script';
//////////////////////////////////////////////////
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
// Importing Components
import Navbar from '../components/Navbar';
import Sidebar from '../components/Sidebar';
import Home from '../components/Main/Home';
import { ProfileComp } from './profile/[uuid]';
import 'react-date-picker/dist/DatePicker.css';
import 'react-calendar/dist/Calendar.css';

//Importing Containers CSS Files
import '../styles/globals.css';

function MyApp({ Component, pageProps }: AppProps) {
  const router = useRouter();

  const { uuid } = router.query;

  const [hideExtra, setHideExtra] = useState<Number>(1);
  const [loading, setLoading] = useState<Boolean>(true);

  const [isOpen, setIsOpen] = useState<Boolean>(true);

  const [currentMenuItem, setCurrentMenuItem] = useState<Number>(1);

  const [currentFullLengthItem, setCurrentFullLengthItem] = useState<Number>(1);

  // eslint-disable-next-line react-hooks/rules-of-hooks
  const dragItem = useRef<any>();

  // eslint-disable-next-line react-hooks/rules-of-hooks
  const dragOverItem = useRef<any>();

  // eslint-disable-next-line react-hooks/rules-of-hooks
  const [list, setList] = useState([
    {
      id: 1,
      src: <audio id='hoverSoundClip'>
        <source src="audio/1.mp3" />
        Your browser is not invited for super fun audio time.
      </audio>,
      name: "Projects",
    },
    {
      id: 2,
      src: <audio id='hoverSoundClip'>
        <source src="audio/2.mp3" />
        Your browser is not invited for super fun audio time.
      </audio>,
      name: "My Priorities",
    },
    {
      id: 3,
      src: <audio id='hoverSoundClip'>
        <source src="audio/3.mp3" />
        Your browser is not invited for super fun audio time.
      </audio>,
      name: "People",
    },
    {
      id: 4,
      src: <audio id='hoverSoundClip'>
        <source src="audio/4.mp3" />
        Your browser is not invited for super fun audio time.
      </audio>,
      name: "Tasks I've Assigned",
    },
    {
      id: 5,
      src: <audio id='hoverSoundClip'>
        <source src="audio/5.mp3" />
        Your browser is not invited for super fun audio time.
      </audio>,
      name: "My goals",
    },
    {
      id: 6,
      src: <audio id='hoverSoundClip'>
        <source src="audio/6.mp3" />
        Your browser is not invited for super fun audio time.
      </audio>,
      name: "Manager Tasks",
    }
  ]);

  useEffect(() => {
    console.clear();
    console.log('routeChangeStart', router.pathname);
    if (router.pathname === "/login" ||
      router.pathname === "/signup" ||
      router.pathname === "/forgot-password" ||
      router.pathname === "/reset-password" ||
      router.pathname === "/verify-email" ||
      router.pathname === "/createProject"
    ) {
      setHideExtra(0);
    }
    else if (
      router.pathname == `/profile/[uuid]`
      || router.pathname === '/profile'
    ) {
      setHideExtra(2);
    }
    else {
      setHideExtra(1);
    }
    setLoading(false);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [router.pathname]);

  return (
    <>
      <Head>
        <meta charSet="utf-8" />
        <meta name="description" content="A chat app built with Next JS,redis,Node JS and Express" />
        <meta name="keywords" content="ChatApp,NextJS,Redis,NodeJS,Express,Realtime" />
        <meta name="author" content="Muhammad-Bilal-7896" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#000000" />

        <title>Log in - Asana</title>
      </Head>

      <section>
        {
          ((hideExtra == 1) && !loading) ? (
            <div className={styles.container}>
              {/* <Head>
                  <title>Home - Project Management Software</title>
                  <meta name="description" content="Generated by create next app" />
                  <link rel="icon" href="/logocopy.ico" />
                  </Head> 
              */}

              <main className={styles.main}>
                <Navbar isOpen={isOpen} setIsOpen={setIsOpen} />
                <div className='d-flex'>
                  <Sidebar currentMenuItem={currentMenuItem} setCurrentMenuItem={setCurrentMenuItem} isOpen={isOpen} setIsOpen={setIsOpen} />

                  <div className={`${styles.rightSideContainer} ${(isOpen) ? (styles.shrinkContainer) : (styles.expandContainer)}`}>
                    {/* Home Page */}
                    <section className={(currentMenuItem === 1) ? ("") : ("d-none")}>
                      <Home />
                    </section>

                    {/* My Tasks Page */}
                    <section className={(currentMenuItem === 2) ? ("") : ("d-none")}>
                      <br />
                      <h3 style={{ marginLeft: 30, marginTop: 5, color: "black", fontWeight: "lighter" }}>My Tasks</h3>
                    </section>

                    {/* Inbox Page */}
                    <section className={(currentMenuItem === 3) ? ("") : ("d-none")}>
                      <br />
                      <h3 style={{ marginLeft: 30, marginTop: 5, color: "black", fontWeight: "lighter" }}>Inbox</h3>
                    </section>

                    {/* Reporting Page */}
                    <section className={(currentMenuItem === 4) ? ("") : ("d-none")}>
                      <br />
                      <h3 style={{ marginLeft: 30, marginTop: 5, color: "black", fontWeight: "lighter" }}>Reporting</h3>
                    </section>

                    {/* Portfolios Page */}
                    <section className={(currentMenuItem === 5) ? ("") : ("d-none")}>
                      <br />
                      <h3 style={{ marginLeft: 30, marginTop: 5, color: "black", fontWeight: "lighter" }}>Portfolios</h3>
                    </section>

                    {/* Goals Page */}
                    <section className={(currentMenuItem === 6) ? ("") : ("d-none")}>
                      <br />
                      <h3 style={{ marginLeft: 30, marginTop: 5, color: "black", fontWeight: "lighter" }}>Goals</h3>
                    </section>
                  </div>
                </div>
              </main>

              <footer className={styles.footer}>
                {/* 
              <a
                  href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                   Powered by{' '}
                <span className={styles.logo}>
                <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                </span>
              </a> 
            */}
              </footer>
            </div>
          ) : (hideExtra == 2 && !loading) ? (
            <div className={styles.container}>
              {/* <Head>
                <title>Home - Project Management Software</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logocopy.ico" />
                </Head> 
            */}

              <main className={styles.main}>
                <Navbar isOpen={isOpen} setIsOpen={setIsOpen} />
                <div className='d-flex'>
                  <Sidebar currentMenuItem={0} setCurrentMenuItem={setCurrentMenuItem} isOpen={isOpen} setIsOpen={setIsOpen} />

                  <main className={`${styles.rightSideContainer} ${(isOpen) ? (styles.shrinkContainer) : (styles.expandContainer)}`}>
                    <ProfileComp />
                  </main>

                </div>
              </main>

              <footer className={styles.footer}>
                {/* 
            <a
                href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
              >
                 Powered by{' '}
              <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
              </span>
            </a> 
          */}
              </footer>
            </div>
          ) : (
            <></>
          )
        }
      </section>
      <Component {...pageProps} />
      <Script
        type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.5.0/mdb.min.js"
      ></Script>
    </>
  )
}
export default MyApp;