import React, { useState, useEffect } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
// Importing Components
import Navbar from '../components/Navbar';
import Sidebar from '../components/Sidebar';

const Home: NextPage = () => {
  const [isOpen, setIsOpen] = useState<Boolean>(true);

  const [currentMenuItem, setCurrentMenuItem] = useState<Number>(1);

  return (
    <div className={styles.container}>
      <Head>
        <title>Home - Project Management Software</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logocopy.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar isOpen={isOpen} setIsOpen={setIsOpen} />
        <div className='d-flex'>
          <Sidebar currentMenuItem={currentMenuItem} setCurrentMenuItem={setCurrentMenuItem} isOpen={isOpen} setIsOpen={setIsOpen} />

          <div className={styles.rightSideContainer}>
            {/* Home Page */}
            <section className={(currentMenuItem === 1) ? ("") : ("d-none")}>
              <br />
              <h3 style={{ marginLeft: 30, marginTop: 5, color: "black", fontWeight: "lighter" }}>Home</h3>
            </section>

            {/* My Tasks Page */}
            <section className={(currentMenuItem === 2) ? ("") : ("d-none")}>
              <br />
              <h3 style={{ marginLeft: 30, marginTop: 5, color: "black", fontWeight: "lighter" }}>My Tasks</h3>
            </section>

            {/* Inbox Page */}
            <section className={(currentMenuItem === 3) ? ("") : ("d-none")}>
              <br />
              <h3 style={{ marginLeft: 30, marginTop: 5, color: "black", fontWeight: "lighter" }}>Inbox</h3>
            </section>

            {/* Reporting Page */}
            <section className={(currentMenuItem === 4) ? ("") : ("d-none")}>
              <br />
              <h3 style={{ marginLeft: 30, marginTop: 5, color: "black", fontWeight: "lighter" }}>Reporting</h3>
            </section>

            {/* Portfolios Page */}
            <section className={(currentMenuItem === 5)? ("") : ("d-none")}>
              <br />
              <h3 style={{ marginLeft: 30, marginTop: 5, color: "black", fontWeight: "lighter" }}>Portfolios</h3>
            </section>

            {/* Goals Page */}
            <section className={(currentMenuItem === 6) ? ("") : ("d-none")}>
              <br />
              <h3 style={{ marginLeft: 30, marginTop: 5, color: "black", fontWeight: "lighter" }}>Goals</h3>
            </section>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        {/* <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a> */}
      </footer>
    </div>
  )
}
export default Home
