import React, { useState, useEffect } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
// Importing Components
import Navbar from '../components/Navbar';
import Sidebar from '../components/Sidebar';

const Home: NextPage = () => {
  const [isOpen, setIsOpen] = useState<Boolean>(true);

  return (
    <div className={styles.container}>
      <Head>
        <title>Home - Project Management Software</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logocopy.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar isOpen={isOpen} setIsOpen={setIsOpen} />
        <Sidebar isOpen={isOpen} setIsOpen={setIsOpen} />
      </main>

      <footer className={styles.footer}>
        dsa
      </footer>
    </div>
  )
}

export default Home
