import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/ContainerCss/Login.module.css';

const Login: NextPage = () => {
    return (
        <div style={{ backgroundColor: "green" }} className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <section className={styles.login_box}>
                    <Image
                        src="/logo.png"
                        alt="Asana"
                        width={121}
                        height={24}
                    />
                    <h2 className={styles.login_title}>Log in to Asana</h2>
                </section>
            </main>

            <footer className={styles.footer}>

            </footer>
        </div>
    )
}

export default Login;
