import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
// importing icons
import { FcGoogle } from "react-icons/fc";
import { FaFacebookF, FaTwitter } from "react-icons/fa";
import { VscGithub } from "react-icons/vsc";

import LoginButton from "../components/LoginButton";
import styles from "../styles/ContainerCss/Login.module.css";

const Login: NextPage = () => {
    return (
        <div style={{ backgroundColor: "green" }} className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <section className={styles.login_box}>
                    <Image src="/logo.png" alt="Asana" width={121} height={24} />
                    <h2 className={styles.login_title}>Log in to Asana</h2>
                    {/* Icons Section */}
                    <section>
                        <LoginButton
                            Text="Continue With Google"
                            Icon={<FcGoogle size={25} />}
                        />
                        <LoginButton
                            Text="Continue With Facebook"
                            Icon={<FaFacebookF color="#3b5998" size={25} />}
                        />
                        <LoginButton
                            Text="Continue With Twitter"
                            Icon={<FaTwitter color="#00acee" size={25} />}
                        />
                        <LoginButton
                            Text="Continue With Github"
                            Icon={<VscGithub size={25} />}
                        />
                        <form action="#">
                            <div className={styles.form_group}>
                                <div style={{ textAlign: "left" }}>
                                    <label htmlFor="email" style={{ fontSize: "20px", marginTop: "30px" }}>Email</label>
                                </div>
                                <input
                                    type="email"
                                    name="email"
                                    id="email"
                                    className={`form-control form-control-lg ${styles.form_control}`}
                                    placeholder="Enter your email"
                                />
                            </div>
                            <div className={styles.form_group}>
                                <div style={{ textAlign: "left", marginTop: "20px" }}>
                                    <label htmlFor="password" style={{ fontSize: "20px" }}>Password</label>
                                </div>
                                <input
                                    type="password"
                                    name="password"
                                    className={`form-control form-control-lg ${styles.form_control}`}
                                    id="password"
                                    placeholder="Enter your password"
                                />
                            </div>
                            <div className={styles.form_group}>
                                <button
                                    className={`btn btn-primary btn-lg btn-block ${styles.btn_login_email}`}
                                >
                                    Log In
                                </button>
                            </div>
                        </form>
                    </section>
                    {/* Icons Section */}
                </section>
            </main>

            <footer className={styles.footer}></footer>
        </div>
    );
};

export default Login;
